// CivicEye – Admin Demo Issues Data
// This file is loaded by admin-panel.html

const DEMO_ISSUES = [
  {
    id: 'issue-001',
    category: 'Roads',
    title: 'Large pothole on MG Road near bus stop',
    description: 'A very large pothole has formed near the main bus stop on MG Road. It is causing accidents for two-wheelers and damaged a car\'s tyre yesterday. Urgent action needed.',
    location: 'MG Road, Sector 17, Chandigarh',
    status: 'Pending',
    date: '01 Apr 2026',
    reporter: 'Rajesh Kumar',
    votes: 47,
    aiScore: 93,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-002',
    category: 'Roads',
    title: 'Broken road divider causing accidents',
    description: 'Road divider on Industrial Road is broken and protruding dangerously. Two accidents have already been reported near this spot this week.',
    location: 'Industrial Road, Phase 2, Mohali',
    status: 'In Progress',
    date: '29 Mar 2026',
    reporter: 'Anita Sharma',
    votes: 31,
    aiScore: 88,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-003',
    category: 'Roads',
    title: 'No street lights on entire stretch – dangerous at night',
    description: 'The entire 800-metre stretch from Sector 21 chowk to Sector 22 market has no functional street lights for the past 3 weeks. Women and elderly feel unsafe.',
    location: 'Sector 21-22 Road, Chandigarh',
    status: 'Pending',
    date: '28 Mar 2026',
    reporter: 'Vikram Rao',
    votes: 64,
    aiScore: 79,
    isDelayed: true,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-004',
    category: 'Garbage',
    title: 'Garbage overflowing near market area',
    description: 'The garbage bin near Sector 22 market is overflowing for 5 days. Foul smell, flies swarming, and health hazard for nearby shop owners and customers.',
    location: 'Sector 22 Market, Chandigarh',
    status: 'Pending',
    date: '02 Apr 2026',
    reporter: 'Priya Mehta',
    votes: 52,
    aiScore: 96,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-005',
    category: 'Garbage',
    title: 'Illegal dumping on vacant plot – burning garbage',
    description: 'People are illegally dumping garbage on a vacant municipal plot near residential colony. Locals have started burning the waste, causing air pollution.',
    location: 'Sector 38, Chandigarh',
    status: 'In Progress',
    date: '31 Mar 2026',
    reporter: 'Suman Singh',
    votes: 29,
    aiScore: 85,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-006',
    category: 'Water Supply',
    title: 'No water supply for 4 days in Sector 44',
    description: 'Entire colony has been without piped water supply for 4 consecutive days. Multiple complaints made to water board but no action. Residents buying expensive water cans.',
    location: 'Sector 44, Chandigarh',
    status: 'Pending',
    date: '30 Mar 2026',
    reporter: 'Mandeep Kaur',
    votes: 89,
    aiScore: 91,
    isDelayed: true,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-007',
    category: 'Water Supply',
    title: 'Major pipe burst – water flooding road',
    description: 'Underground water pipe burst near Sector 15 park. Water gushing out and flooding the road for past 2 days. Road is submerged and vehicles cannot pass.',
    location: 'Sector 15 Park Road, Chandigarh',
    status: 'In Progress',
    date: '02 Apr 2026',
    reporter: 'Harjeet Singh',
    votes: 71,
    aiScore: 97,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-008',
    category: 'Electricity',
    title: 'Transformer exploded – no power since 2 days',
    description: 'The colony transformer exploded 2 days ago damaging nearby poles. 150+ households are without electricity. Food spoiling in refrigerators. Extreme heat.',
    location: 'Zirakpur Colony, Punjab',
    status: 'Pending',
    date: '01 Apr 2026',
    reporter: 'Gaurav Jain',
    votes: 103,
    aiScore: 94,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-009',
    category: 'Electricity',
    title: 'Exposed live wires hanging dangerously low',
    description: 'Live electric wires are hanging very low on Panchkula road after last week\'s storm. Very dangerous – children on cycles at risk. Immediate action required.',
    location: 'Sector 7, Panchkula',
    status: 'Pending',
    date: '02 Apr 2026',
    reporter: 'Neha Gupta',
    votes: 58,
    aiScore: 98,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: null
  },
  {
    id: 'issue-010',
    category: 'Others',
    title: 'Public park benches broken and unusable',
    description: 'Most of the benches in Sector 28 park are broken and rusty. Elderly people and children cannot sit. Park is in poor condition overall with broken pathways too.',
    location: 'Sector 28 Park, Chandigarh',
    status: 'Resolved',
    date: '25 Mar 2026',
    reporter: 'Sunita Rao',
    votes: 22,
    aiScore: 81,
    isDelayed: false,
    beforeImage: null,
    afterImage: null,
    resolveComment: 'All benches repaired and painted. Park pathway also fixed.',
    resolvedAt: '01 Apr 2026'
  }
];
